polls/urls.py
from django.conf.urls import url
from polls.views import round, random_round, article_new, process_normal_round_form, \
    process_random_round_form
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.profile, name='profile'),
    url(r'^round/(?P<round_id>[0-9]+)/$', round, name='round'),
    url(r'^process_normal_round_form/(?P<round_id>[0-9]+)/(?P<article_id>[0-9]+)/$',
        process_normal_round_form,
        name='process_normal_round_form'),
    url(r'^process_random_round_form/(?P<round_id>[0-9]+)/$',
        process_random_round_form,
        name='process_random_round_form'),
    url(r'^random_round/(?P<pk>[0-9]+)/$', random_round, name='random_round'),
    url(r'^article/new', article_new, name='article_new'),
]

polls/models.py
import datetime
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.utils import timezone
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


# Articles and Phrases
class Round(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now)
    finished_date = models.DateTimeField(null=True)
    is_random = models.BooleanField(default=False)

    def __str__(self):
        isrand = 'Random round ' if self.is_random else 'Normal round '
        finisheddate = 'not finished' if not self.finished_date else self.finished_date.strftime('%d-%m-%Y %H:%M')

        return isrand + finisheddate


class Article(models.Model):
    body = models.CharField(max_length=40000)

    def __str__(self):
        return "Article " + str(self.pk)


class ArticleEval(models.Model):
    NOT_EVALUATED = -1
    NON_CREDIBLE = 0
    CREDIBLE = 1

    Rate = (
        (0, 'Artykuł jest niewiarygodny'),
        (1, 'Artykuł jest wiarygodny')
    )

    is_credible = models.IntegerField(choices=Rate)
    article = models.OneToOneField(Article, on_delete=models.CASCADE)
    round = models.OneToOneField(Round, on_delete=models.CASCADE, null=True)

class Phrase(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    body = models.CharField(max_length=4000)

    def __str__(self):
        return self.body

class PhraseEval(models.Model):
    NON_CREDIBLE = 0
    NEUTRAL = 1
    CREDIBLE = 2

    Rate = (
        (NON_CREDIBLE, 'Zdanie jest niewiarygodne'),
        (NEUTRAL, 'Zdanie jest neutralne'),
        (CREDIBLE, 'Zdanie jest wiarygodne'),
    )

    phrase = models.OneToOneField(Phrase, on_delete=models.CASCADE)
    rate = models.IntegerField(choices=Rate, blank=True, null=True)
    round = models.ForeignKey(Round, on_delete=models.CASCADE, null=True)


class RandomPhraseEval(models.Model):
    NONSENSE = -1
    NON_CREDIBLE = 0
    NEUTRAL = 1
    CREDIBLE = 2

    Rate = (
        (NONSENSE, 'Zdania nie można ocenić'),
        (NON_CREDIBLE, 'Zdanie jest niewiarygodne'),
        (NEUTRAL, 'Zdanie jest neutralne'),
        (CREDIBLE, 'Zdanie jest wiarygodne'),
    )

    phrase = models.ForeignKey(Phrase, on_delete=models.CASCADE)
    rate = models.IntegerField(choices=Rate, blank=True, null=True)
    round = models.ForeignKey(Round, on_delete=models.CASCADE, null=True)


@receiver(post_save, sender=Article)
def create_phrases_with_article(sender, instance, **kwargs):
    if kwargs.get('created', False):
        sentences = instance.body.split("\n")
        for sentence in sentences:
            if len(sentence) > 1:
                ph = Phrase.objects.create(article=instance, body=sentence)
                ph.save()

polls/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Article, ArticleEval, Round, PhraseEval


class ArticleEvalForm(forms.ModelForm):

    class Meta:
        model = ArticleEval
        fields = ('is_credible',)


class PhraseEvalForm(forms.ModelForm):

    class Meta:
        model = PhraseEval
        fields = ('rate',)


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = '__all__'


class RoundForm(forms.ModelForm):

    class Meta:
        model = Round
        fields = '__all__'

class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

polls/views.py
import random
from itertools import chain

from datetime import datetime

from django.db import connection, IntegrityError
from django.contrib import messages
from django.forms import modelformset_factory, Select
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import redirect, render

from .forms import ArticleForm, ArticleEvalForm, UserCreateForm

from polls.models import Round, Article, Phrase, PhraseEval, RandomPhraseEval
from polls.email_list import email_list

def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('polls:profile'))
    else:
        return HttpResponseRedirect(reverse('login'))


def delete_unfinished_rounds(request):
    unfinished_rounds = request.user.round_set.filter(finished_date__isnull=True)
    unfinished_rounds.delete()


def login_error(request):
    return HttpResponseRedirect(reverse('login'))


def signup(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            if email in email_list:
                form.save()
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password, email=email)
                login(request, user)
                return redirect('polls:profile')
            else:
                messages.error(request, ("Nie można założyć konta. Skontaktuj się z osobą, od której \
                 otrzymałeś link do strony tej rejestracji, lub upewnij się, że wpisałeś poprawny adres email."))
                return redirect('signup')
    else:
        form = UserCreateForm()
    return render(request, 'polls/signup.html', {'form': form})


@login_required
def profile(request):
    delete_unfinished_rounds(request)
    user = request.user
    rounds = user.round_set.all()

    if request.method == 'POST':
        return choose_round(request)

    return render(request, 'polls/profile.html', {
        'rounds': rounds,
    })

def choose_round(request):
    all_noncred = get_phrases_with_evals(0)
    all_neu = get_phrases_with_evals(1)
    all_cred = get_phrases_with_evals(2)

    new_round = Round(
                 user=request.user,
                 created_date=timezone.now(),
                 is_random=random.getrandbits(1)
                )
    new_round.save()

    if len(all_noncred + all_neu + all_cred) == 0:
        new_round.is_random = 0
        new_round.save()
        return HttpResponseRedirect(reverse('polls:round', args=(new_round.id,)))
    elif new_round.is_random:
        return HttpResponseRedirect(reverse('polls:random_round', args=(new_round.id,)))
    else:
        return HttpResponseRedirect(reverse('polls:round', args=(new_round.id,)))


def get_random_article():
    # choose random article and pass it to the context
    ids_domain = Article.objects.filter(articleeval__isnull=True).values_list('id', flat=True)
    random_id = random.choice(ids_domain)
    article = Article.objects.get(pk=random_id)
    return article


def get_phrases_with_evals(cred_value):
    query = '''
        SELECT distinct phrase.id FROM polls_phrase AS phrase

        LEFT JOIN polls_phraseeval AS ph_eval ON phrase.id = ph_eval.phrase_id AND ph_eval.rate = %s
            LEFT JOIN polls_randomphraseeval AS r_ph_eval ON phrase.id = r_ph_eval.phrase_id

        WHERE r_ph_eval.id IS NULL and ph_eval.id IS NOT NULL;
    '''

    with connection.cursor() as cursor:
        cursor.execute(query, [cred_value])
        res = cursor.fetchall()
        result = []
        for row in res:
            result.append(row[0])

        return result


def get_random_phrases_set():
    all_noncredible_ph_ids = get_phrases_with_evals(0)
    all_neutral_ph_ids = get_phrases_with_evals(1)
    all_credible_ph_ids = get_phrases_with_evals(2)

    subset_len = 11

    try:
        subset_credible_ph_ids = random.sample(all_credible_ph_ids, subset_len)
    except ValueError:
        subset_credible_ph_ids = all_credible_ph_ids

    subset_credible_phrases = Phrase.objects.filter(id__in=subset_credible_ph_ids)

    try:
        subset_noncredible_ph_ids = random.sample(all_noncredible_ph_ids, subset_len)
    except ValueError:
        subset_noncredible_ph_ids = all_noncredible_ph_ids

    subset_noncredible_phrases = Phrase.objects.filter(id__in=subset_noncredible_ph_ids)

    try:
        subset_neutral_ph_ids = random.sample(all_neutral_ph_ids, subset_len)
    except ValueError:
        subset_neutral_ph_ids = all_neutral_ph_ids

    subset_neutral_phrases = Phrase.objects.filter(id__in=subset_neutral_ph_ids)

    random_phrases = list(chain(subset_credible_phrases, subset_noncredible_phrases, subset_neutral_phrases))

    return random_phrases


@login_required
def round(request, round_id, **kwargs):
    survey_round = Round.objects.get(pk=round_id)

    try:
        article = get_random_article()
    except IndexError:
        survey_round.is_random = 1
        survey_round.save()
        return HttpResponseRedirect(reverse('polls:random_round', args=(survey_round.id,)))


    phrases = article.phrase_set.all()
    art_eval_form = ArticleEvalForm(request.POST or None)

    try:
        for phrase in phrases:
            PhraseEval.objects.create(phrase=phrase, rate=None, round=survey_round)
    except IntegrityError:
        pass

    phrase_eval_queryset = survey_round.phraseeval_set.all()
    PhraseEvalFormSet = modelformset_factory(PhraseEval, fields=('rate',),
                                             widgets={'rate': Select(attrs={'required': True})},
                                             max_num=len(phrases)-1
                                             )
    formset = PhraseEvalFormSet(request.POST or None,
                                queryset=phrase_eval_queryset,
                                initial=[{'rate': None}]
                                )

    return render(request, 'polls/round.html', context={
        'round': survey_round,
        'article': article,
        'art_eval_form': art_eval_form,
        'formset': formset
    })

def process_normal_round_form(request, round_id, article_id):
    survey_round = Round.objects.get(pk=round_id)
    article = Article.objects.get(pk=article_id)

    phrase_eval_queryset = survey_round.phraseeval_set.all()
    PhraseEvalFormSet = modelformset_factory(PhraseEval, fields=('rate',),
                                             widgets={'rate': Select(attrs={'required': True})},
                                             max_num=len(phrase_eval_queryset) - 1
                                             )
    formset = PhraseEvalFormSet(request.POST or None, queryset=phrase_eval_queryset, initial=[{'rate': None}])
    art_eval_form = ArticleEvalForm(request.POST or None)

    if formset.is_valid() and art_eval_form.is_valid():
        for form in formset:
            form.cleaned_data['id'].rate = form.cleaned_data['rate']
            form.cleaned_data['id'].save()

        art_eval = art_eval_form.save(commit=False)
        art_eval.round = survey_round
        art_eval.article = article
        art_eval.save()

        survey_round.finished_date = datetime.now()
        for ph_ev in survey_round.phraseeval_set.all():
            if ph_ev.rate == None:
                ph_ev.delete()
        survey_round.save()

        messages.success(request, 'Dziękujemy za wypełnienie ankiety!')
        return HttpResponseRedirect(reverse('polls:profile'))
    else:
        messages.error(request, formset.errors)
        return HttpResponseRedirect(reverse('polls:profile'))


@login_required
def random_round(request, **kwargs):
    survey_round = Round.objects.get(pk=kwargs['pk'])
    phrases = get_random_phrases_set()

    if len(phrases) == 0:
        messages.error(request,
                       'Wygląda na to, że wszystkie zdania mają już oceny. Dziękujemy za udział w badaniu!')
        return HttpResponseRedirect(reverse('polls:profile'))


    for phrase in phrases:
        RandomPhraseEval.objects.create(phrase=phrase, rate=None, round=survey_round)

    phrase_eval_queryset = survey_round.randomphraseeval_set.all()
    PhraseEvalFormSet = modelformset_factory(RandomPhraseEval, fields=('rate',),
                                             widgets={'rate': Select(attrs={'required': True})},
                                             max_num=len(phrases)-1
                                             )
    formset = PhraseEvalFormSet(request.POST or None, queryset=phrase_eval_queryset, initial=[{'rate': None}])

    return render(request, 'polls/random_round.html', {
        'round': survey_round,
        'formset': formset
    })


def process_random_round_form(request, round_id):
    survey_round = Round.objects.get(pk=round_id)
    phrase_eval_queryset = survey_round.randomphraseeval_set.all()
    PhraseEvalFormSet = modelformset_factory(RandomPhraseEval, fields=('rate',),
                                             widgets={'rate': Select(attrs={'required': True})},
                                             max_num=len(phrase_eval_queryset)-1
                                             )
    formset = PhraseEvalFormSet(request.POST or None, queryset=phrase_eval_queryset, initial=[{'rate': None}])

    if formset.is_valid():
        for form in formset:
            form.cleaned_data['id'].rate = form.cleaned_data['rate']
            form.cleaned_data['id'].save()

        survey_round.finished_date = datetime.now()
        for ph_ev in survey_round.randomphraseeval_set.all():
            if ph_ev.rate == None:
                ph_ev.delete()

polls/templates/polls/_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Badanie wiarygodności</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "polls/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "polls/css/style.css" %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>

        <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'polls:profile' %}">Profil użytkownika {{ user }}</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'logout' %}">Wyloguj</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->

        {% for message in messages %}
          <div class="alert {{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
              <div class="clean-error-list"></div>
            {{ message }}
          </div>
        {% endfor %}


        {% block content %}
        {% endblock %}

    <!-- jQuery -->
    <script src="{% static 'polls/js/jquery.js' %}"></script>
    <script src="{% static 'polls/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'polls/js/my.js' %}"></script>
</body>

polls/templates/polls/article_edit.html
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            Zapisz
        </button>
    </form>
{% endblock %}

polls/templates/polls/login_error.html
<p>You're not logged in!</p>

polls/templates/polls/profile.html
{% extends "polls/_layout.html" %}
{% block content %}

<div class="container">
    <p style="color: green">
        {% if msg %}
            {{ msg }}
        {% endif %}
    </p>
    <br>
    <div class="row">
        <div class="col-md-6 manual">
            <h1>INSTRUKCJA</h1>

            <div class="paragraph">
                <p>Po kliknięciu przycisku "Stwórz nową rundę" zostanie wylosowana jedna z dwóch typów ankiet:
                    <ol>
                        <li>
                            OCENA BEZKONTEKSTOWA - polega na ocenie niepowiązanych ze sobą zdań, każdego z osobna.
                        </li>
                        <li>
                            OCENA KONTEKSTOWA - polega na ocenie zdań tworzących cały artykuł, a także na całościowej ocenie artykułu.
                        </li>
                    </ol>
                 </p>
            </div>
            <div class="paragraph">
                <b>Zdania</b> można ocenić w trzystopniowej skali:
                <ul>
                    <li>
                        <div class="green">WIARYGODNE</div>
                        <ul>
                            <li>jest wiarygodne, nie budzi zastrzeżeń</li>
                            <li>zawiera informację</li>
                        </ul>
                    </li>
                    <li>
                        <div class="yellow">NEUTRALNE</div>
                        <ul>
                            <li>jest bezwartościowe informacyjnie</li>
                            <li>jest niejasno sprecyzowane</li>
                            <li>zawiera perswazję <u>zgodną</u> z obowiązującą wiedzą medyczną</li>
                        </ul>
                    </li>
                    <li>
                        <div class="red">NIEWIARYGODNE</div>
                        <ul>
                            <li>jest niewiarygodne</li>
                            <li>zawiera nieprawdziwą i/lub niesprawdzoną informację</li>
                            <li>zawiera perswazję <u>sprzeczną</u> z obowiązującą wiedzą medyczną</li>
                        </ul>
                    </li>
                </ul>
                <p><b>ZDANIA NIE MOŻNA OCENIĆ</b>
                gdy bez kontekstu jest niezrozumiałe.</p>
            </div>

            <div class="paragraph">
                <b>Artykuł</b> można ocenić w dwustopniowej skali:
                <ul>
                    <li>
                        <div class="green">WIARYGODNY</div>
                        <ul>
                            <li>nie budzi zastrzeżeń</li>
                            <li>nie nawołuje do postępowania w sprzeczności z obowiązującą wiedzą medyczną</li>
                            <li>chociaż częściowo zawiera konkretną wiedzę medyczną</li>
                        </ul>
                    </li>
                    <li>
                        <div class="red">NIEWIARYGODNY</div>
                        <ul>
                            <li>budzi zastrzeżenia</li>
                            <li>nawołuje do postępowania sprzecznego z obowiązującą wiedzą medyczną</li>
                            <li>nie zawiera żadnej konkretnej wiedzy medycznej (artykuł jest "o niczym")</li>
                            <li>zawiera nieprawdziwe i/lub niesprawdzone informacje</li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="paragraph">
                Ankiety należy wypełniać powołując się na własną wiedzę medyczną oraz zawodową intuicję. Dziękuję!
            </div>
        </div>

        <div class="col-md-6">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-default">
                    Stwórz nową rundę
                </button>
            </form>
            <br>
            <br>
            Wziąłeś udział w następujących rundach:
            <br>
            {% if not rounds %}
            <p class="red-alert"> Nie wypełniłeś jeszcze żadnej ankiety. Kliknij w "stwórz nową rundę". </p>
            {% endif %}

            <ol>
                {% for round in rounds %}
                    <li class="blue">
                        rozpoczęta: {{ round.created_date }} <br>
                        zakończona: {{ round.finished_date }} <br>
                        zdania oceniane
                        {% if round.is_random %}
                            bezkontekstowo
                        {% else %}
                            kontekstowo <br>
                            Oceniony artykuł o ID {{ round.articleeval.article.id }}
                        {% endif %}
                    </li>
                {% endfor %}
            </ol>
            <br>
        </div>
    </div>

    <footer>
    Administratorka strony - Aleksandra Nabożny <br>
        kontakt: s13495@pjwstk.edu.pl
    </footer>
</div>
<!-- /.container -->


{% endblock %}

polls/templates/polls/random_round.html
{% extends "polls/_layout.html" %}
{% load static %}
{% block content %}

<div class="upper-instruction-container">
    <div id="upper-instruction">
        <div class="container">
            <div class="row instruction-row">
                <div class="col-md-4">
                    <h4 class="green">ZDANIE WIARYGODNE</h4>
                    <ul>
                        <li>jest wiarygodne, nie budzi zastrzeżeń</li>
                        <li>zawiera informację</li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <h4 class="yellow">ZDANIE NEUTRALNE</h4>
                    <ul>
                        <li>jest bezwartościowe informacyjnie</li>
                        <li>jest niejasno sprecyzowane</li>
                        <li>zawiera perswazję <u>zgodną</u> z obowiązującą wiedzą medyczną</li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <h4 class="red">ZDANIE NIEWIARYGODNE</h4>
                    <ul>
                        <li>jest niewiarygodne</li>
                        <li>zawiera nieprawdziwą i/lub niesprawdzoną informację</li>
                        <li>zawiera perswazję <u>sprzeczną</u> z obowiązującą wiedzą medyczną</li>
                    </ul>
                </div>
            </div>
            <div class="row instruction-row">
                <p class="text-center"><b>ZDANIA NIE MOŻNA OCENIĆ</b></p>
                <p class="text-center">gdy bez kontekstu jest niezrozumiałe.</p>
            </div>
        </div>
    </div>

    <button id="toggle-instruction" class="btn btn-default">POKAŻ INSTRUKCJĘ</button>
</div>

<div class="container round-container">
    <form  action="{% url 'polls:process_random_round_form' round.id %}" method="post">
        {% csrf_token %}

        {{ formset.management_form }}
        {% for form in formset %}
            {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
            <div class="row phrase-block">
                <div class="col-md-8">
                    {{ form.instance.phrase.body }}
                </div>
                <div class="col-md-4">
                    {{ form.rate }}
                </div>
            </div>

        {% endfor %}

        <div class="centering">
            <div class="center">
                <button type="submit" class="btn btn-default">
                    Zapisz
                </button>
            </div>
        </div>
    </form>
<footer>
aleksandra.nabozny@gmail.com
</footer>
</div>
<!-- /.container -->

{% endblock %}

polls/templates/polls/round.html
{% extends "polls/_layout.html" %}
{% load static %}
{% block content %}

<div class="upper-instruction-container">
    <div id="upper-instruction">
        <div class="container">
            <div class="row instruction-row">
                <div class="col-md-4">
                    <h4 class="green">ZDANIE WIARYGODNE</h4>
                    <ul>
                        <li>jest wiarygodne, nie budzi zastrzeżeń</li>
                        <li>zawiera informację</li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <h4 class="yellow">ZDANIE NEUTRALNE</h4>
                    <ul>
                        <li>jest bezwartościowe informacyjnie</li>
                        <li>jest niejasno sprecyzowane</li>
                        <li>zawiera perswazję <u>zgodną</u> z obowiązującą wiedzą medyczną</li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <h4 class="red">ZDANIE NIEWIARYGODNE</h4>
                    <ul>
                        <li>jest niewiarygodne</li>
                        <li>zawiera nieprawdziwą i/lub niesprawdzoną informację</li>
                        <li>zawiera perswazję <u>sprzeczną</u> z obowiązującą wiedzą medyczną</li>
                    </ul>
                </div>
            </div>
            <div class="row instruction-row">
                <div class="col-md-6">
                    <h4 class="green">ARTYKUŁ WIARYGODNY</h4>
                    <ul>
                        <li>nie budzi zastrzeżeń</li>
                        <li>nie nawołuje do postępowania w sprzeczności z obowiązującą wiedzą medyczną</li>
                        <li>chociaż częściowo zawiera konkretną wiedzę medyczną</li>
                    </ul>
                </div>
                <div class="col-md-6">
                    <h4 class="red">ARTYKUŁ NIEWIARYGODNY</h4>
                    <ul>
                        <li>budzi zastrzeżenia</li>
                        <li>nawołuje do postępowania sprzecznego z obowiązującą wiedzą medyczną</li>
                        <li>nie zawiera żadnej konkretnej wiedzy medycznej (artykuł jest "o niczym")</li>
                        <li>zawiera nieprawdziwe i/lub niesprawdzone informacje</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <button id="toggle-instruction" class="btn btn-default">POKAŻ INSTRUKCJĘ</button>
</div>

<div class="container round-container">
    <br>
    <p> Article ID: {{ article.id }} </p>
    <br>

    <form action="{% url 'polls:process_normal_round_form' round.id article.id %}" method="post">
        {% csrf_token %}

        {{ formset.management_form }}
        {% for form in formset %}
            {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
            <div class="row phrase-block">
                <div class="col-md-8">
                    {{ form.instance.phrase.body }}
                </div>
                <div class="col-md-4">
                    {{ form.rate }}
                </div>
            </div>

        {% endfor %}

        <div class="centering">
            <div class="center">
                <p class="article-eval">
                    Oceń wiarygodność całego artykułu
                    {{ art_eval_form.is_credible }}
                </p>
                <button type="submit" class="btn btn-default">
                    Zapisz
                </button>
            </div>
        </div>
    </form>

    <footer>
        aleksandra.nabozny@gmail.com
    </footer>
</div>
<!-- /.container -->

{% endblock %}